### ISSUE TITLE
Masking

### ISSUE THREAD

**Issue by IanShelanskey** [raganmd/Beneath#17]

**Comment by raganmd** [comment]
Masking out performers, or scenic elements? This this a global mask that goes over the entire render?

**Comment by IanShelanskey** [comment]
It seems like this the ability to mask globally. The ability to mask "inside"  geometry like a phase 2 deal.

**Comment by raganmd** [comment]
Added in beneath/components/output.tox
There is now a movie file in here that's a placeholder for a mask that will be applied to both left and right eye.
