### ISSUE TITLE
Where does Audio live?

### ISSUE THREAD

**Issue by IanShelanskey** [raganmd/Beneath#23]
In layer/Cue/At sound?

**Comment by raganmd** [comment]
**Steve**, when you have a chance can you chime in on this one?

Our real question here is about if we need an audio playback system that we line-out out to you, if we just need to be able to trigger you, or some combination.

It sounds like there will be some of the same talking head interviews that were in Brief Anniversary, and I couldn't remember how you guys solved that problem last time. My memory is both things... that you started by trying to calculate the delay, but moved to just embedding the audio in the movie file. But my memory of all of that is very fuzzy.

Anyway, we're fine either way, but how we build playback and our data structure for storing cues will be dependent on how we're working with you on this - so let's nail down something we feel good about.

**Comment by srchrist** [comment]
Hey-
It'd be great if audio that's sync'd with video lived with the video, and was passed (digital or analog) over to sound.

I'm not sure if I'll be running a Dante system yet, I'm still working on the details of that, but if I am that'd be a really easy setup. 

If I'm running an analog system again, it'll still be easy, but with a few more cables. I'd get you an interface that outputs to a console that I'd mix into the system.

That enough info to go on for now? Let me know if you need/want more.


One thing we'll have to address is how the hell we get it mixed into 11.4 surround, but we'll get there.


Best,

Steve

**Comment by raganmd** [comment]
all the answers to the questions! Love it.
